### PR TITLE
Feature/factsheets

### LINKED ISSUE #90: [Factsheets] MF - software - External optimizer
@ludee Do we want to give examples in the info text (e.g. pyomo) or do we want to make options or a text field?

### LINKED ISSUE #94: [Factsheets] MF - Openess - data provided
Rename "some" to "example data"? @ludee

### LINKED ISSUE #95: [Factsheets] MF - Openess - Cooperative programming
@ludee 

Cooperative or collaborative programming?

How do we define cooperative / collaborative programming? Chance to join the developer group (as in the info text)? Chance to make pull request on GitHub or other platforms?

There is a tick box (yes / no). Should we allow the comment, that the collaboration will be possible soon? Another tick box?

### LINKED ISSUE #100: [Factsheets] MF General information, Number of developers
Spelling mistake in form and in the fact sheet: Number of dev**e**lopers

### LINKED ISSUE #419: Rework Framework Factsheets
The Framework Factsheets need a havy rework.
open_MODEX will contribute the content. 

List all existing FFS issues here:

Provide new structure: @srhbrnds

### PR DESCRIPTION
**Pull request by solar-c**
Closes #95, closes #419, closes #94, closes #100,  closes #90

### CODE REVIEW

**Comment by 4lm** [comment]
Hi @solar-c,

I'm reviewing this pull request and have a few remarks.

#95: good!

#419: 

In Framework ...

... in "Overview":

- "Last updated" should be a DateField but is a CharField
- under "License", "BSD 3-clause 'New' or 'Revised' license" is missing

... in "General Information":

- in https://next.rl-institut.de/s/6ZXwQkXFSSxMQAf "General Information" is named "Basic "Information". What is correct?
- in "contact" https://next.rl-institut.de/s/6ZXwQkXFSSxMQAf is not consistent, e.g. "website" is in contact and "website" also in options of "contact". IMO, I would leave it like it is right now! What do you think?
- in "contact" there are also the options "phone" and "other, which are missing. I would leave it like it is right now, it's not needed IMO! What do you think?
- in "Geographical Scope", "Points/degree of abstraction" should be "single-project" says https://next.rl-institut.de/s/6ZXwQkXFSSxMQAf
- "Inital Release Date" should be a DateField but is a CharField

... in Openness:

- under "License", "BSD 3-clause 'New' or 'Revised' license" is missing

... Model Building:

- in "Cost Inclusion", "OFuel handling" should be "Fuel handling"

#94: good!

#100: good!

#90: good!

PS: I made a commit in which I added the migrations for #419, they were missing, no biggy!

**Comment by solar-c** [comment]
- "Last updated" and inital release are now DateFields

- added BSD 3 to License options

- since all other factsheets use the term 'general information' I decided to stick with it :) no exceptions!

- agreed concerning contact/website/phone. Let's wait for the feedback, if necessary more options can be added / remodeled to multi-select or similar. I think potential users have to multi-select enough ;) 

- fixed Typos in "geographical scope" and "Fuel handling"

Thank you :smile:

**Comment by 4lm** [comment]
@solar-c,

changes look good!

One more thing, I recognized that in Factsheets > (Frameworks|Scenarios) the the sidebar info is at the bottom (in Factsheets > Models the sidebar is shown correctly):

image

**Comment by Bachibouzouk** [comment]
@solar-c : can you update `version/changelogs/current.md` with the changes made in this PR?

**Pull request merged**
