### PR TITLE
Connect plotly graph to API

### PR DESCRIPTION
**Pull request by MGlauer**

### CODE REVIEW

**Comment by MGlauer** [comment]
I can. But for this I need to know how the column names are passed to the script.

**Comment by Bachibouzouk** [comment]
> I can. But for this I need to know how the column names are passed to the script.

I was thinking to save the column names in the options field of the View instance under `x` and `y` (you can see it in #499, I pushed my latest changes)

**Comment by MGlauer** [comment]
Then I will include it in this pr.

**Comment by MGlauer** [comment]
Ok, the columns for graphs are loaded from the `current_view` variable now.

**Pull request merged**
