### PR TITLE
Fix bug in data versioning

### LINKED ISSUE #320: Invalid table names
When creating a table via the API, containing upper-case characters an error occurs (due to postgres restrictions). However, in the dataviewer on the platform the title of the wrongly named table was visible including an invalid link. 
error
invalid

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Closes #320 

* Move meta table creation to single function
* Check existence of table before creation

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@MGlauer - I created the PR with your branch (it was linked in the issue as its solution but it was not merged yet). However, I'm not sure about the conflict resolution in the `api/actions.py` file.

**Comment by Bachibouzouk** [comment]
@MGlauer - this is old code, but the issue it is still opened. Can you decide how to solve the conflicts?

**Comment by Bachibouzouk** [comment]
@MGlauer - Can you take action on this one please?

**Comment by 4lm** [comment]
@Bachibouzouk you assigned me as reviewer, do you want me to review this or are you only waiting for the action of @MGlauer?

**Comment by MGlauer** [comment]
Neither ;) I requested you review, as @Bachibouzouk can not be assigned because he opened this PR and I can not review it, because I developed it.

**Comment by 4lm** [comment]
So, shall I merge it?

**Comment by Bachibouzouk** [comment]
> So, shall I merge it?

By the github etiquette, you shall approve the PR first. Then, if the person who opened the PR does not react to merge it within a few hours, you should inquiry if they noticed you approved the PR :)

**Comment by 4lm** [comment]
> By the github etiquette, you shall approve the PR first. Then, if the person who opened the PR does not react to merge it within a few hours, you should inquiry if they noticed you approved the PR :)

Understood :) will do!

**Pull request merged**
