### PR TITLE
Move CI to Actions

### PR DESCRIPTION
**Pull request by johannwagner**
I moved over the CI workflow from Travis to GitHub Actions. 

Someone, probably @MGlauer, needs to remove travis integration from this repository. Indeed, we used travis-ci.org to integrate and it is shut down since the 15th of June.

I also fixed some environment-related bugs within the tox configuration, that was not important until now due to a loose security setting on the postgres. 

I also use a prepared image for the postgres container right now, that I currently maintain at https://github.com/OpenEnergyPlatform/oeplatform-postgres. This is the same repo as https://github.com/OpenEnergyPlatform/oeplatform-deploy, but I wanted to rename it because the repository name is going to be the image name. Docker image is published here (https://github.com/OpenEnergyPlatform/oeplatform-postgres/pkgs/container/oeplatform-postgres)  and also automagically built by GitHub actions on each tag.

Open Tasks:

- [x] ~Mark jobs as Required to merge a PR (https://stackoverflow.com/a/58655352) (Some Administrator)~
- [x] Remove Travis Integration (Some Administrator)
- [x] Split oeplatform-deploy and oeplatform-postgres correctly. (@johannwagner)
  + There is some documentation that is located at oeplatform-deploy having nothing to do with this repository. We can keep it there and move all postgres-related stuff to oeplatform-postgres.
  + Later on, we could use this repo to document a full-docker setup for using the OEP.

### CODE REVIEW

**Comment by johannwagner** [comment]
We need to enable the "Required" flags for PRs to develop after merging this. It is not visible right now.

**Comment by johannwagner** [comment]
@christian-rli If you approve this change, J would be happy to merge it.

**Review by christian-rli — APPROVED** [review]
Everything looks reasonable. Thanks for the quick implementation and feel free to merge :)

**Comment by johannwagner** [comment]
I also added the required flags for pull requests.

**Pull request merged**
