### PR TITLE
Update Tutorials UI and extend content

### LINKED ISSUE #736: There is no "back to tutorials" button
When I am viewing a specific tutorial there is no "back to tutorials" button or similar. I think this would be helpful to have.

### PR DESCRIPTION
**Pull request by jh-RLI**
Changes acording to https://github.com/OpenEnergyPlatform/tutorial/issues/135

### Additional changes:

- [x] make "back to tutorials" button more visible and visible for all users 
    - closes #736

### CODE REVIEW

**Comment by jh-RLI** [comment]
- Added the new fields to the model 
- Updated form to create a tutorial with new fields 
- Updated available fields in static and dyn. tutorial 

@johannwagner 
Context data is available in the template. I created a template [meta.json](https://github.com/OpenEnergyPlatform/tutorial/blob/oep_integration/extend_meta-json_content/template/tutorial_metadata.json) with all fields and possible values (also see this [PR](https://github.com/OpenEnergyPlatform/tutorial/pull/139)). I need to update all the meta.json for each tutorial. Please use some test tutorial with the template data until there is an update.

**Comment by jh-RLI** [comment]
I just noticed that levels in dyn. tutorails are just stored as numbers in the db. Maybe this causes problems, because the levels in static tutorials are stored as text. I can change this but the existing tutorials will not be affected.
see https://github.com/OpenEnergyPlatform/oeplatform/blob/8b4b833241ade5ce1a48eb9328c30e99beffc4ee/tutorials/models.py#L11

**Comment by jh-RLI** [comment]
Not sure why the CI fails

**Comment by MGlauer** [comment]
> Not sure why the CI fails

This was due to a change in the newest SQLAlchemy version and has been fixed on develop

**Comment by jh-RLI** [comment]
> * Added the new fields to the model
> * Updated form to create a tutorial with new fields
> * Updated available fields in static and dyn. tutorial
> 
> @johannwagner
> Context data is available in the template. I created a template [meta.json](https://github.com/OpenEnergyPlatform/tutorial/blob/oep_integration/extend_meta-json_content/template/tutorial_metadata.json) with all fields and possible values (also see this [PR](https://github.com/OpenEnergyPlatform/tutorial/pull/139)). I need to update all the meta.json for each tutorial. Please use some test tutorial with the template data until there is an update.

@johannwagner  I have updated the tutorial meta.jsons in https://github.com/OpenEnergyPlatform/tutorial/pull/139.

**Comment by johannwagner** [comment]
Thanks a lot, will take care of this, soon!

**Comment by johannwagner** [comment]
I updated the tutorials UI. 

Screenshot from 2021-04-07 09-23-21

**Comment by johannwagner** [comment]
Note: https://github.com/OpenEnergyPlatform/tutorial/pull/139 needs to be merged and **UPDATED** within this PR before merging.

**Comment by johannwagner** [comment]
@christian-rli I fixed the open issues and would like to merge this PR into development. Please rereview this PR.

**Review by christian-rli — APPROVED** [review]
Looks good. I need to rethink my GitHub settings. Somehow I did not notice this PR before the release.

**Comment by christian-rli** [comment]
I meant to merge this, but the latest change introduced a conflict and frankly I am unsure how to solve this particular conflict with directories. As you were just endowed with admin powers, you have my blessings to merge this PR after solving the conflict @johannwagner .

Also I noticed that you're using the submodule under the old generic repository name `examples` and not `tutorial`. I guess this would mostly be a cosmetic fix, and since we already have a `tutorials` folder, the value added would not be huge, I suppose. Still I just wanted to mention my slight preference for `tutorial`.

**Pull request merged**
