### PR TITLE
show sandbox tables in interface but not in schema view

### LINKED ISSUE #1308: show sandbox tables in interface, but not in schema view
## Description of the issue

Describe the problem in as much detail as possible. 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by wingechr**
### Automation

Closes #1308

### Reviewer

* first commit is only only code cleanup/formatting
* manual tests:
  * https://openenergy-platform.org/dataedit/view/scenario must show
  * https://openenergy-platform.org/dataedit/view/sandbox must give 404
  * https://openenergy-platform.org/dataedit/view/sandbox/test_table_xyz should show, if table has been created

### CODE REVIEW

**Review by jh-RLI — APPROVED** [review]
Works as expected ! Thanks for the formatting.

**Comment by jh-RLI** [comment]
@wingechr i always have to create the sandbox Schema manually. Is this the same for you?

**Comment by wingechr** [comment]
> @wingechr i always have to create the sandbox Schema manually. Is this the same for you?

only when creating a new oedb instance, right? or what is `always`?

**Comment by wingechr** [comment]
sandbox should still stay a separate schema even after we resolve them, so we can add it to alembic

**Pull request merged**
