### PR TITLE
Styling of scenario bundles detail view

### PR DESCRIPTION
**Pull request by bmlancien**
## Summary of the discussion

Started styling of scenario bundles detail view

### Added
- Update styling of scenario bundles detail view [(#1435)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1435)

### Automation
Is part of #1282 #1283 #1284 

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform-code/) 

### Reviewer
- [x] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [x] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
@bmlancien I resolved a conflict in the changelog. You can simply pull the changes it sould not effect your work.

**Comment by bmlancien** [comment]
Done @jh-RLI :)

**Comment by bmlancien** [comment]
Hi @jh-RLI, I think you can now have a look at the PR. I tried to reorganize parts of the code. This can definitely be improved still. There are things I wanted to do but was not able to:

- Add icons to tabs (Scenarios, Publications,...)
- Remove the empty horizontal scrollbars below the inputs in edit view, e.g. below the Institutions dropdown

Responsiveness could also be improved on smaller screens. But maybe this is ok for now?

**Comment by jh-RLI** [comment]
Looks great :) Thanks you!

I think the icons and scrollbars can be added later.

The only thing i noticed is this small thing: 
If this is hard to fix i will just merge the PR now and we can fix this later :)

on openenergyplatform.org
image

in this branch
image

**Review by jh-RLI — APPROVED** [review]
Great work! Very good to see that everything becomes more modular and clean :)

**Comment by jh-RLI** [comment]
FYI @adelmemariani
I merge this branch now

**Comment by bmlancien** [comment]
Hey @jh-RLI, on my side this working properly. Maybe a problem with the cache? The view and edit buttons should look like that:

chrome-capture-2023-9-30

**Comment by jh-RLI** [comment]
You are correct, some changes have not been there due to some git issue. It´s now visible to me ;)

**Pull request merged**
