### PR TITLE
oemetadata migration (dataedit.models.tables oemetadata field)

### PR DESCRIPTION
**Pull request by jh-RLI**
- reuse results pushed to https://github.com/OpenEnergyPlatform/oeplatform/commit/ff6c5a279c49f15c4de9fcd0fa5f07fdf150be3a

### CODE REVIEW

**Comment by wingechr** [comment]
i can only do this next week

**Comment by jh-RLI** [comment]
Sure take your time I'll test this on my local setting for now, but would be more confident if you also test this :) (next week ofc)

**Review by jh-RLI — COMMENTED** [review]
Great thanks for showing me how to do this @wingechr - the PR is now past the draft state, isnt it?

**Comment by wingechr** [comment]
yea, probably.

**Pull request merged**
