### PR TITLE
fix/dataedit-afterrelease-fixes

### LINKED ISSUE #321: Filtering Data
As a   user I want to filter data (across all data) to find data.

### LINKED ISSUE #331: search for keywords
As a   user, I would like to search for keywords in order to get suitable scenarios   displayed.

### LINKED ISSUE #373: Add Link at 'Schema' to navigate backwards
When entering Database -> Dataview = Schemas -> e.g climate -> cosmoclmgrid
I now see 'climate.cosmoclmgrid' and can click on 'climate' to navigate one level up -> I now see 'Schema: climate' but I can not click on 'Schema' to navigate backwards. I have to click Database -> Dataview

ToDo:
1.) make 'Schema' clickable to navigate backwards
2.) Add Schema somewhere on the level of 'cosmoclmgrid' to be able to navigate straight away backwards
3.) Make Layout consitent:  'Schema: climate' vs. 'climate.cosmoclmgrid'  it sould be the same best ':'

### LINKED ISSUE #585: Tags: list of tags in sidebar not "complete"
The list of tags in the sidebar doen't seem to display the most-helpful tags anymore. 
It seems to list the first tags in alphabetical order. Clicking tags works, but using the filter field above to find and apply tags does not.

### LINKED ISSUE #614: [Metaissue] Rework Dataedit/Tags
This issue is for planning the modification of the tag module in dataedit. Further issues are documented in the linked PullRequest. 

The rework/modification also includes the implementation of functionality to create tags automatically if they are described in an open energie metadata(oem) file. 

Below I have documented the current state based on the functions that can be found via the frontend. In the following I describe the problems that have been identified. Unfortunately, the description is in german:

#### Funktion macht nicht/ nicht genau das was sie soll:
- Ort: dataedit/Schema; Button_Name: Apply Filters
	- Beschreibung: Wenn ein Nutzer Tags auswählt und den Button klickt, dann werden die Schemas, 
	  die Tags enthalten, angezeigt - das ist okay. Problem ist, dass wenn man ein Schema anklickt 
	  werden alle Tabellen aufgelistet, nicht nur die die das gesuchte Tag/Tags enthalten.

- Ort: dataedit/Schema/Tabellen (Tags, die in der Auflistung zu den jeweiligen Tabellen angezeigt werden); Button_Name: tag_symbol
	- Beschreibung: Wenn man auf ein Tag klickt, das in der Liste zu einer Tabelle zugeordnet ist, kommt man auf die 
	  "edit tags" Seite. Meiner Meinung nach erwartet der Nutzer hier entweder:
		 - eine Erklärung zu dem Tag 
		 - möchte das Tag zum filtern auswählen
		 - möchte weitere Tags zu der Tabelle hinzufügen
		 - möchte das Tag von der Tabelle entfernen
	- Lösung: angehängte tags nicht klickbar machen oder eindeutige Funktion definieren
		 

____________________________________________________________
#### Funktion ist "nicht" auffindbar/strukturell schlecht angelegt:
- Ort: dataedit/schema/tabelle; botton_name: kleines grünes + unter der Überschrift "Tags"
	- Beschreibung: Das hinzufügen von Tags zu einer Tabelle ist sehr schlecht zu finden. Der Apply und Edit Button
	  ist schlecht sichtbar und nicht in einer eigenen Zeile. Die Funktionen sind funktional nicht voll zusammenhängend.
	  Es ist vielleicht praktisch, hier gleich einen neuen Tag erstellen zu können, jedoch sollten sich die Funktionen 
	  auf so einem niedrigen Level auch hauptsächlich auf die Tabelle beziehen. 
	- Lösung: 
		- Apply button belassen, aber besser sichtbar machen.
		- Edit button entwerder entfernen oder zusätzlich belassen
		- Besser beschreiben wie tags entfernt werden (wegnehmen des häckchens -> apply)
		- Edit button sollte bereits vorher existieren (vielleicht direkt dataedit/schema unter "Tag filter" sektion)

- Ort: dataedit/schema button_name: fehlt (Schema)
	- Beschreibung: Es gibt keine interaktive möglichkeit von der Auflistung der Tabellen in einem Schmea wieder zurück 
	  zu der gesamtübersicht der Schemas zu gelangen.
	- Lösung:
		- einfach wäre es die übreschrift Schema:Schema_name das Schema klickbar zu machen und auf die vorherige
			Seite weiterzuleiten

___________________________
#### Verbesserungspotenziale:

- Tags auf schema/tabellen Level könnten eingegrenzt werden, indem nur die Tags angezeigt werden,
	die in dem aktuellen Schema enthalten sind/ bereits verwendet wurden. Andere Tags sollten ja kein Ergebnis
        zurückgeben.

Überblick GUI und Funktionen - Tagsmodul

____________________________

### PR DESCRIPTION
**Pull request by johannwagner**
This branch contains fixes from the Design rework.

The following issues are fixed with this PR:
Closes #321 
Closes #373 
Closes #585 
Closes #331 
Closes #614

### CODE REVIEW

**Comment by jh-RLI** [comment]
I have linked several issues concerning the dataedit.

**Comment by jh-RLI** [comment]
We are planning a restructuring of the tag functions until the next release (03.08). Mainly the existing buttons must be more visible for the user and the functions should be tested again to fix the bugs from the issues.

**Comment by MGlauer** [comment]
@johannwagner Is this ready for review? If not, what is still missing?

**Comment by christian-rli** [comment]
To preempt my review: Link back to schemas works. View shows more than 10 tags. Tags filter tables. I didn't encounter a problem with this branch and think it can be merged.

**Comment by jh-RLI** [comment]
If you click on a tag that is already linked to a table, users will still be directed to the tag editing page. see #639

**Comment by johannwagner** [comment]
@MGlauer This is ready to merge, iirc. There were some discussions about a specific topic I do not remember about. If there are no concerns, we can merge this.

**Comment by MGlauer** [comment]
@johannwagner I think there are still some migrations missing. Could you add those and remove the WIP flag from this PR?

**Comment by johannwagner** [comment]
Will do!

**Comment by johannwagner** [comment]
I added some migrations, but I am not sure, if those are correct. They were generated by `python manage.py makemigrations`...

@MGlauer

**Pull request merged**
