### PR TITLE
static files instead of external resources and remove deprecated file 

### PR DESCRIPTION
**Pull request by wingechr**

### CODE REVIEW

**Review by jh-RLI — COMMENTED** [review]
@wingechr I get this when viewing the dataedit/schema and table pages. 
image

If i then open the tag select dropdown there are no tags visible for a few seconds and it throws another error. Everything works fine after that first hickup. 

I think this eats a lot of spagetti :) Great work.

**Comment by wingechr** [comment]
the source mapping is only for development and not needed,so i removed it from the js file

**Review by jh-RLI — APPROVED** [review]
Now everything works as expected.

**Comment by jh-RLI** [comment]
I removed a deprecated file and just added it to the fasttrack branch. The file contained deprecated settings and is not related to the static files.

**Pull request merged**
