### PR TITLE
Feature/remove django tags #970

### LINKED ISSUE #970: remove unused code
@Ludee @jh-RLI @adelmemariani: please comment/add

* [ ] scenario factsheets (disable)
* [x] literature
* [x] tags table in django database
* [ ] right box with "If you find bugs or if you have ..."
* [ ] remove outdated meta editor widget from dataview

### PR DESCRIPTION
**Pull request by wingechr**
closes #970

### CODE REVIEW

**Comment by wingechr** [comment]
mh... no, i am not sure about the factsheets at all. so let's not merge just yet, I will have a second look. 
But in the code, there was no reference to the django Tag class anywhere I could see.

**Comment by wingechr** [comment]
@Ludee I checked and on my test system, the django Tag model can be deleted and the Tags on the factsheets are not affected.
Can you verify this on the production somehow?

**Comment by wingechr** [comment]
also closes #785

**Comment by jh-RLI** [comment]
@wingechr I also think this is safe to be merged. I will add the changelog and merge it after that.

**Pull request merged**
