### PR TITLE
Implement reworked topic overview page

### LINKED ISSUE #1201: [Topics Page] Implement reworked UI
We created a prototype of the OEP-Topics page (forma schma page).
- [x] implement mockup
- [ ] connect with backend
-  [ ] gather feedback
- [ ] release
- [ ] Check if consistent with https://wiki.openmod-initiative.org/wiki/Database_schema

### PR DESCRIPTION
**Pull request by jh-RLI**
Update the Topic page UI

Closes #1201

### CODE REVIEW

**Comment by jh-RLI** [comment]
Thanks @bmlancien this looks great. It would be great if the `<div class="topics__row"> `  can automatically create a new row if the elements fill the current row. 

If this is possible, we would just need one of these and then we can automatically create a topic card for every topic.
https://github.com/OpenEnergyPlatform/oeplatform/blob/15a42b7e1957d7e8741afb6c31a5e0ce472d1ae4/dataedit/templates/dataedit/dataedit_schemalist.html#L94-L120

**Comment by jh-RLI** [comment]
@bmlancien Now you can pull my changes :) .

**Comment by jh-RLI** [comment]
@bmlancien please tell me if you are done with your changes from your point of view :)

**Comment by jh-RLI** [comment]
Thanks a lot! I will have a look and merge it as it is if i don't find anything major missing. You can pick up work in a new branch. 

Yes that is normal, you just have tables in the model draft schema/topic in your local database.


We need to update the changelog also.

**Comment by jh-RLI** [comment]
On my laptop this looks quite big with normal zoom. But the rest is perfectly fine and very visible.

image

**Comment by bmlancien** [comment]
@jh-RLI You can merge if that's ok for you.

**Comment by jh-RLI** [comment]
Thanks  :) I will check one last time and merge it.

**Pull request merged**
