### PR TITLE
Inital implementation of video content within tutorial section

### PR DESCRIPTION
**Pull request by johannwagner**
This is another pull request to implement videos within the tutorial section.
I cherry-picked the other commits from the broken branch and squashed them together.

Right now, it is not fully discussed, if this should be merged within this state.

I propose to close https://github.com/OpenEnergyPlatform/oeplatform/pull/516 in favor of this PR.

### CODE REVIEW

**Comment by christian-rli** [comment]
This branch works on my local instance and I got a test video to play. Is there a particular reason why it's still a work in progress? I'd like it to be part of the next release :)

**Comment by johannwagner** [comment]
No, there is no reason, why this is not able to merge. I think, this is pending on @MGlauer.

**Comment by MGlauer** [comment]
Is there any documentation on how to use the form to include video content? At least in the "Add tutorial" form it does not seem obvious.

**Comment by MGlauer** [comment]
Ah, ok - when linking to a youtube video you would need the embed link. I guess this is not something any unexperienced user would do. Is there any way to make it more convenient?

**Comment by johannwagner** [comment]
Yup, I did a small google research and you may be able to convert it, if it is not an embed link. Should we try this? 

Reference: https://stackoverflow.com/questions/29781974/convert-youtube-link-into-an-embed-link

**Comment by MGlauer** [comment]
Yes, this would improve the usability massively.

**Comment by johannwagner** [comment]
I will take care of this feature request.

**Comment by christian-rli** [comment]
thanks, you two.

**Comment by MGlauer** [comment]
I guess this can be easily done with a simple regex: 

```
^https:\/\/www\.youtube\.com\/watch\?v=(?P<id>[A-z0-9]+)$
```
and then
```
"https://www.youtube.com/embed/{id}"
```

Question is, whether there are any services that are a bit less thirsty when it comes to personal data. @christian-rli any ideas?

**Comment by johannwagner** [comment]
We decided to implement YouTube as a first step and may add other video on-demand streaming portals later on.

**Pull request merged**
