### PR TITLE
Content

### PR DESCRIPTION
**Pull request by adelmemariani**
Ontology overview page updated content + latest version #750

### CODE REVIEW

**Review by christian-rli — CHANGES_REQUESTED** [review]
Running this branch, using a clean new install of the database, I get a 404 error when clicking on ontology - overview. So I don't see the changes and get an error instead. It works fine in the develop branch. Can you fix that? Alternatively, can you explain why that won't be a problem when merged and deployed?

My Error:

Page not found (404)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/ontology/
Raised by: 	ontology.views.OntologyVersion

Using the URLconf defined in oeplatform.urls, Django tried these URL patterns, in this order:

    ^api/
    ^ ^robots.txt$
    ^ ^$ [name='index']
    ^ ^about/$ [name='index']
    ^ ^faq/$ [name='index']
    ^ ^discussion/$ [name='index']
    ^ ^contact/$ [name='index']
    ^ ^legal/privacy_policy/$ [name='index']
    ^ ^legal/tou/$ [name='index']
    ^ captcha/
    ^user/
    ^factsheets/
    ^dataedit/
    ^literature/
    ^ontology/ ^$

The current path, ontology/, matched the last one.

**Comment by christian-rli** [comment]
In order for this branch to work, a local copy of the ontology, located in the path ONTOLOGY_FOLDER (defined in securitysettings.py) is needed. My folder structure was /ontologies/oeo.1.6.1 and I used these files:
[oeo.zip](https://github.com/OpenEnergyPlatform/oeplatform/files/7077715/oeo.zip)

**Comment by christian-rli** [comment]
@adelmemariani take care not to push your local env to GitHub :)

**Comment by johannwagner** [comment]
@christian-rli The correct fix would be rewriting the history to not pollute the entire repository. Otherwise, the files are kept within the repository and you can access them by jumping to the commit before the deletion.

**Review by christian-rli — APPROVED** [review]

**Comment by christian-rli** [comment]
> @christian-rli The correct fix would be rewriting the history to not pollute the entire repository. Otherwise, the files are kept within the repository and you can access them by jumping to the commit before the deletion.

True that @johannwagner . I don't feel confident about that though. Feel free to help me out :)

In other news: @adelmemariani is going to approach you for including the oeo graph viewer into the OEP. We thought that we had our meeting tomorrow, but it'll be next week, so he'll talk to you directly. I want to include this in the release, so the release is waiting fot that. (@han-f that's why you won't see any changes yet, if you were counting on them already).

**Comment by han-f** [comment]
> I want to include this in the release, so the release is waiting fot that. (@han-f that's why you won't see any changes yet, if you were counting on them already

Thanks @christian-rli for including it into the release and also communicating the delay, which I find helpful.

**Comment by christian-rli** [comment]
> @christian-rli I prepared my local repo to fix this, BUT there are two other feature branches using the same commit.

Thank you @johannwagner ! This problem is something I am unable to help with, so could you coverse directly with @adelmemariani to take care of a clean history?

**Comment by johannwagner** [comment]
I fixed the branch mess.

**Comment by christian-rli** [comment]
Thanks for the fixes! I looked into the branch again. When selecting Overview from the ontology menu, I get a 404 error, which does not happen in the develop branch. Why is that and does it matter @adelmemariani 


Page not found (404)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/ontology/
Raised by: 	ontology.views.OntologyVersion

Using the URLconf defined in oeplatform.urls, Django tried these URL patterns, in this order:

    ^api/
    ^ ^robots.txt$
    ^ ^$ [name='index']
    ^ ^about/$ [name='index']
    ^ ^faq/$ [name='index']
    ^ ^discussion/$ [name='index']
    ^ ^contact/$ [name='index']
    ^ ^legal/privacy_policy/$ [name='index']
    ^ ^legal/tou/$ [name='index']
    ^ captcha/
    ^user/
    ^factsheets/
    ^dataedit/
    ^literature/
    ^ontology/ ^$

The current path, ontology/, matched the last one.

**Pull request merged**
