### PR TITLE
WIP: fix/design rework welcome page

### PR DESCRIPTION
**Pull request by johannwagner**
I implemented the first part of the mockup. 
I have to contact Bryan about some things, I will report feedback at this point.

localhost_8000_(iPad Pro)

### CODE REVIEW

**Comment by Ludee** [comment]
Can you please also implement the updated design for the landing page.

2019_09_26_OEP_HP_Desktop

**Comment by 4lm** [comment]
So,

#448 showed, the correct branch to evaluate the design of @johannwagner is his working branch `fix/design-rework-welcome-page`. @Ludee please check this branch out and give your opinion as earlier requested by @MGlauer, so that @johannwagner can implement changes and/or go on with the missing design parts ... thx!

**Comment by 4lm** [comment]
Hi @johannwagner,

I have some comments/questions about the inner workings of the redesign. But first I will give a little context for better understanding:

Two weeks ago I started working on this project, one of my tasks since then is the further improvement (@Bachibouzouk started to work on this) of the metadata edit view `meta_edit.html`.

For this I started a new branch: [`feature/improve-meta-edit-view-ux`](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/improve-meta-edit-view-ux)

For the metadata edit view we wanted to have a left sidebar, which is sticky in desktop view and on top in mobile view and also get rid of the right sidebar. Here is a screenshot of the yet unfinished revamp:

image

For this, I rewrote the block structure of the layout to be more flexibel and fullfill our needs:

image

I'm lying a little bit here :wink:, because I didn't won't to destroy the given layout structure, the block layout looks more like this:

image

@Bachibouzouk and I then decided to tackle this from in a more general way and to derive a new branch in which I solely focus on the rearrangement of the block layout structure of the templates: [`feature/modularize-templating`](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/modularize-templating)

I also opened a PR in which I layout my design decisions: https://github.com/OpenEnergyPlatform/oeplatform/pull/447

Enough context :smile:, now to my actual issue! I tried to merge your work in this branch with the code from my branch, the code got quite complicated, because I tried to stay compatible to your code design decisions and also fulfill my needs of a more flexibel block structure layout. In the end I aborted the merge and thought, it's time to contact you directly and ask you about your opinion how to further progress here ...

What I need for is a more flexibel block structure layout, like described above, to implement for example stuff like the metadata edit view. But I also want keep your new responsive design implementation!

What do you think? How shall we progress further?

**Comment by johannwagner** [comment]
Thanks for your clearification, but I am not the right person to decide this. 

You may want to sync with @MGlauer and @bmlancien, @MGlauer is authorized to give instructions to me.

**Comment by MGlauer** [comment]
For me the main question is whether this design goes well with what @bmlancien has in mind for the redesign? I would leave this decision to him as I am definitely no authority when it comes to design.

I don't really see the need for a navigation bar on a relatively small form, but I am no UX expert either so, no substantial objections from my side.

**Comment by 4lm** [comment]
OK, I will ask @bmlancien and report back!

**Comment by 4lm** [comment]
> I don't really see the need for a navigation bar on a relatively small form [...]

Maybe my description was not good enough. The way I structures the block templating it's super flexibel and you can for each use case have different layouts, e.g.: all sidebars, only left|right sidebar no sidebars, no header, no footer etc.

**Comment by bmlancien** [comment]
> OK, I will ask @bmlancien and report back!

I think the idea from @4lm is good, because it would give the OEP website more flexibility in the future, as we might want different kinds of layouts, e.g. main content only, or main content and sidebars. This would allow us to design/change page layouts more easily.

@johannwagner Could you take this into account when working on the homepage too? If you are using a base template it would be good to include all the elements listed by @4lm even if there are not visible on the homepage.

**Comment by 4lm** [comment]
> If you are using a base template it would be good to include all the elements listed by @4lm 

@johannwagner, if you like you can cherry pick from this branch: https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/modularize-templating

**Comment by johannwagner** [comment]
So, if I am correct: 
I will rebase this branch onto develop and going to merge this into develop to be able to create new branches for subsites.
Afterwards, we can decide, what is going to happen with #447?
@MGlauer

**Comment by johannwagner** [comment]
Nevermind, I think, this does not need a merge, because commits on this branch were splitted and cherry-picked by @Bachibouzouk onto develop.

**Comment by johannwagner** [comment]
I propose to close this one.
The changes, which were requested by @bmlancien are implemented in https://github.com/OpenEnergyPlatform/oeplatform/pull/458, because due to the wild cherry picking, this branch is unmergable.

**Comment by Bachibouzouk** [comment]
> I propose to close this one.
> The changes, which were requested by @bmlancien are implemented in #458, because due to the wild cherry picking, this branch is unmergable.

I think this is wise to start again fresh :), I will therefore close this comment.
@johannwagner can you delete the branch ? (I can do it also, but I want to make sure I can by asking you first)

**Pull request closed without merging**
