### PR TITLE
dataedit update tag filter UI

### LINKED ISSUE #614: [Metaissue] Rework Dataedit/Tags
This issue is for planning the modification of the tag module in dataedit. Further issues are documented in the linked PullRequest. 

The rework/modification also includes the implementation of functionality to create tags automatically if they are described in an open energie metadata(oem) file. 

Below I have documented the current state based on the functions that can be found via the frontend. In the following I describe the problems that have been identified. Unfortunately, the description is in german:

#### Funktion macht nicht/ nicht genau das was sie soll:
- Ort: dataedit/Schema; Button_Name: Apply Filters
	- Beschreibung: Wenn ein Nutzer Tags auswählt und den Button klickt, dann werden die Schemas, 
	  die Tags enthalten, angezeigt - das ist okay. Problem ist, dass wenn man ein Schema anklickt 
	  werden alle Tabellen aufgelistet, nicht nur die die das gesuchte Tag/Tags enthalten.

- Ort: dataedit/Schema/Tabellen (Tags, die in der Auflistung zu den jeweiligen Tabellen angezeigt werden); Button_Name: tag_symbol
	- Beschreibung: Wenn man auf ein Tag klickt, das in der Liste zu einer Tabelle zugeordnet ist, kommt man auf die 
	  "edit tags" Seite. Meiner Meinung nach erwartet der Nutzer hier entweder:
		 - eine Erklärung zu dem Tag 
		 - möchte das Tag zum filtern auswählen
		 - möchte weitere Tags zu der Tabelle hinzufügen
		 - möchte das Tag von der Tabelle entfernen
	- Lösung: angehängte tags nicht klickbar machen oder eindeutige Funktion definieren
		 

____________________________________________________________
#### Funktion ist "nicht" auffindbar/strukturell schlecht angelegt:
- Ort: dataedit/schema/tabelle; botton_name: kleines grünes + unter der Überschrift "Tags"
	- Beschreibung: Das hinzufügen von Tags zu einer Tabelle ist sehr schlecht zu finden. Der Apply und Edit Button
	  ist schlecht sichtbar und nicht in einer eigenen Zeile. Die Funktionen sind funktional nicht voll zusammenhängend.
	  Es ist vielleicht praktisch, hier gleich einen neuen Tag erstellen zu können, jedoch sollten sich die Funktionen 
	  auf so einem niedrigen Level auch hauptsächlich auf die Tabelle beziehen. 
	- Lösung: 
		- Apply button belassen, aber besser sichtbar machen.
		- Edit button entwerder entfernen oder zusätzlich belassen
		- Besser beschreiben wie tags entfernt werden (wegnehmen des häckchens -> apply)
		- Edit button sollte bereits vorher existieren (vielleicht direkt dataedit/schema unter "Tag filter" sektion)

- Ort: dataedit/schema button_name: fehlt (Schema)
	- Beschreibung: Es gibt keine interaktive möglichkeit von der Auflistung der Tabellen in einem Schmea wieder zurück 
	  zu der gesamtübersicht der Schemas zu gelangen.
	- Lösung:
		- einfach wäre es die übreschrift Schema:Schema_name das Schema klickbar zu machen und auf die vorherige
			Seite weiterzuleiten

___________________________
#### Verbesserungspotenziale:

- Tags auf schema/tabellen Level könnten eingegrenzt werden, indem nur die Tags angezeigt werden,
	die in dem aktuellen Schema enthalten sind/ bereits verwendet wurden. Andere Tags sollten ja kein Ergebnis
        zurückgeben.

Überblick GUI und Funktionen - Tagsmodul

____________________________

### LINKED ISSUE #678: toep: Explanation on how to use Filters and Tags needs update on schema page
It reads:
_Use the Filters on Tags or try searching for strings that occur in table names. You can combine text and Tags filters to get more precise results. If you filter for multiple Tags, only tables containing all filtered Tags will be displayed._ 

1) If I filter for tags, the list of schemas is reduced to the schemas that hold this tag. It doesn't show the tables. If I then click a schema I see all tables in the schema, not only the ones with the tag. 
Personally, I think it would be neat if the search really showed me all the tables for the search result, but I assume it will for now remain a filtering of schemas only. Thus I suggest to adjust the text to: _If you filter for multiple Tags, only schemas containing  tables with all filtered Tags will be displayed._

2) _Use the Filters on Tags or try searching for strings that occur in table names._
Shouldn't this better read: _Use the Filters on Tags or try searching for **text** that may occur in table names **or in metadata**._ 
Not sure we should use the term 'string' and the text search now also searches across more than only table names. 

PS: 2) could be the same for the explanation that occurs if a user filters within a schema. But 1) would need to read differently (or like the original text) then: _If you filter for multiple Tags, only tables containing all filtered Tags will be displayed._

### LINKED ISSUE #681: toep: Clicking a tag in schema table still leads to 'edit tags'
Clicking a tag in the list with tables in a schema still leads to 'edit tags' rather than to displaying only those tables that have the tag attached. 

see e.g.: http://toep.iks.cs.ovgu.de/dataedit/view/model_draft 
see also #639  - which seems to have been addressed and closed already

### PR DESCRIPTION
**Pull request by jh-RLI**
- When a filter is applied to tags at the dataedit/schema level, clicking on a schema now keeps the http.get parameters
- If an user clicks on a tag label (that is listed on a table) a filter for that single tag is applied as http.get
- Update the filters description text 
 
Closes #614
Closes #681
Closes #678

### CODE REVIEW

**Comment by jh-RLI** [comment]
Maybe there is a better approach using regex.

**Comment by christian-rli** [comment]
Hm. I meant to have a look at this, but something with my setup went wrong and I cannot access my database anymore from within the local OEP. Fixing it might mean just setting up a new database again. Could you maybe review this @johannwagner ?

**Comment by jh-RLI** [comment]
Maybe this helps?
try to run: 
`python manage.py mirror`
if this fails try checking out this branch:
`fix/mirror_schemas`
and repeat the command, that fixed the OEP dataview for me.

**Comment by christian-rli** [comment]
Thank you @jh-RLI our magic trick fixed my database.

**Review by christian-rli — APPROVED** [review]
This fixes #681 , #614 and #678 in my setup. Well done! If there are no objections from @MGlauer or @meisam-booshehri I think you can merge @jh-RLI .

**Pull request merged**
