### PR TITLE
Implement general profile page UI

### PR DESCRIPTION
**Pull request by jh-RLI**
## Summary of the discussion

Implementation of the general user profile ui.

Part of #1218 

### Update
- Update general Profile page UI [(#1300)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1300)

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [Read The Docs](https://oeplatform.readthedocs.io/en/latest/?badge=latest) 

### Reviewer
- [x] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [x] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
I updated all of the profile subpages (tables, review, settings) @bmlancien

My changes are applied to the old profile page (sidebar is still on the right) hope this will not cause to much trouble to you.

Tables, Review pages:
I added a placeholder to the if cases that handel empty fields. 
Search for `<!-- empty or placeholder or just show icon? --> `

Settings page:
I added a placeholder for each field if it is empty and removed the link to the edit page like:
```
{% if profile_user.fullname %}
    {{ profile_user.fullname }}
{% else %}
    No full name added.
{% endif %} 
```

**Comment by bmlancien** [comment]
Hey @jh-RLI, I updated the sidebar:

- Put sidebar to the left side
- Added icons
- Hid items that are not added by the user, because it doesn't add any value to the user to see "Location" or "No location added". To test to see if everything is working, you can add values to the profile
- Kept affiliation but I'm not so sure what it is about
- Also kept the description, but I think we could remove "Description:"

**Comment by jh-RLI** [comment]
Thanks a lot 🥳, I will take a look at the conflicts. I think the conflicts are here because some of the changes have already been applied in the reviewe profile ui branch.

**Comment by bmlancien** [comment]
> I think the conflicts are here because some of the changes have already been applied in the reviewe profile ui branch.

I'm gonna have a look at it

**Comment by bmlancien** [comment]
I think it should be solved now.

**Comment by jh-RLI** [comment]
Yes, I'm :) Thanks for handling this quickly.

**Pull request merged**
