### PR TITLE
Group management view

### LINKED ISSUE #1559: Rework permission group management pages
## Description of the issue

Permission groups are a practical way to manage access to serveral ressources created on the OEP. At the moment they are mainly used to manage table access but it is planned to also use them to manage schenario bundle and factsheet (framework, models) accees. 

## Ideas of solution

The feature is available on the profile page of the oep, but it is hidden in the "Settings" tab. As it is a feature with growing importance, it should be given its own tab. The feature itself is scattered. The user has to navigate through multiple pages and can't navigate back properly. We need to create a mockup for it and rework the feature so that it is usable on a single page. All functionality should be easier for the user to understand. 

In addition, it would be nice to have an overview of which table a group is currently assigned to.

Functions such as Add user should offer automatic completion. 

The authorisation levels that can be assigned to a user should be readable and the rights granted should be transparent/traceable.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### LINKED ISSUE #1607: Improved the user interface for the "Tables" subpage on the profile page.
## Description of the issue

We have developed an updated user interface for the profile pages. This issue is aimed at implementing the UI for the "Tables" subpage.

## Ideas of solution

Mockups for profile page:
https://www.figma.com/file/rWzNf643RnQmI8ODk0zlfO/Database-pages-view?type=design&node-id=605%3A1658&mode=design&t=K3vCIQ7TKrlK19NG-1

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by jh-RLI**
## Summary of the discussion

Describe the findings of the discussion in the issue or meeting.

### Added
- Add a new functionality [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Updated
- Update existing functionality [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Removed
- Remove a broken link [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Automation
Closes #1559
Closes #1607

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform-code/) 

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
@bmlancien I have noticed that the icons are missing in this branch. I assume it's easy to add them back. But I will add the group management page first. Just so we don't forget to add the icons again.

image

**Comment by bmlancien** [comment]
> I have noticed that the icons are missing in this branch

@jh-RLI Do you mean the icons on the tabs? If so, I hid them on smaller screens in order to take less space and not destroy the tab layout after adding a fourth tab (group management). Or do you mean something else?

**Comment by jh-RLI** [comment]
Ah i see. I've seen that they exist, but I didn't notice the difference on smaller screens. We could also only show the icons then

**Comment by bmlancien** [comment]
Alright :) In general I would choose the text over the icons if it's possible, as an icon alone is not always enough to understand what it's about.

**Comment by jh-RLI** [comment]
This related PR https://github.com/OpenEnergyPlatform/oeplatform-postgres/pull/1 should be merged by the time this PR i smerged. I introduces a query that requires a new postgres database extension.

**Pull request merged**
