### PR TITLE
Feature/oe platform homepage link

### PR DESCRIPTION
**Pull request by Dhruvin14**
Interchanged homepage link issue 387 is solved and Issue 382 is working correctly. 
https://github.com/OpenEnergyPlatform/oeplatform/issues/387 
Minimal implementation to add tooltips to table view from metadata; #382  
https://github.com/OpenEnergyPlatform/oeplatform/pull/382

### CODE REVIEW

**Comment by Dhruvin14** [comment]
@Bachibouzouk, we are having conflicts in the same file. 
dataedit/templates/dataedit/dataedit_overview.html

**Comment by Bachibouzouk** [comment]
@Dhruvin14 - First of all thanks for your contribution :)

I already addressed #383 in #430, the conflict you mention stems from #382, which I closed and whose branch you apparently merged into yours. 

It is best practice to have one branch and one PR per issue. You then indicate the issue number in your PR description with one of the [keywords](https://help.github.com/en/articles/closing-issues-using-keywords), so that the issue is closed automatically when the PR is merged :)

What I would do for now is remove the commits. One way to do it (because your commits are small, which is a good thing :)) : 
create a new branch (i.e. `fix/oep-homepage-link`)

**Comment by Bachibouzouk** [comment]
@Dhruvin14 - I just merged a PR in develop, so you should first checkout your local develop branch and pull the changed, then create your new branch from this one. You can call our office if you have questions :)

**Comment by Bachibouzouk** [comment]
@Dhruvin14 - follow these steps to link your repo to this remote

`git remote rename origin old_remote`
`git remote add origin https://github.com/OpenEnergyPlatform/oeplatform.git`
`git pull origin develop`

**Comment by Dhruvin14** [comment]
$ git pull origin develop                                                        
error: Pulling is not possible because you have unmerged files.                  
hint: Fix them up in the work tree, and then use 'git add/rm '             
hint: as appropriate to mark resolution and make a commit.                       
fatal: Exiting because of an unresolved conflict.
--

**Comment by Bachibouzouk** [comment]
> ## $ git pull origin develop
> error: Pulling is not possible because you have unmerged files.
> hint: Fix them up in the work tree, and then use 'git add/rm '
> hint: as appropriate to mark resolution and make a commit.
> fatal: Exiting because of an unresolved conflict.

either copy-paste the file `base/templates/base/base.html` outside the repository, then type
`git reset --hard develop`

or revert changes in all unmerged files you see in your sourcetree

**Comment by Dhruvin14** [comment]
@Bachibouzouk when I use git reset --hard develop 

fatal: ambiguous argument 'develop': unknown revision or path not in the working  tree.                                                                           Use '--' to separate paths from revisions, like this:                            'git  [...] -- [...]'

--

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk when I use git reset --hard develop
> 
> fatal: ambiguous argument 'develop': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git [...] -- [...]'
> 
> --

@Dhruvin14 - then use source tree to reject changes to other files (can you give me the print of  `git status`?)

**Comment by Dhruvin14** [comment]
git status

[git status.txt](https://github.com/OpenEnergyPlatform/oeplatform/files/3616452/git.status.txt)

**Comment by Bachibouzouk** [comment]
@Dhruvin14 

then do 
- `git merge --abort`
- `git checkout master`
- `git branch -D develop`
- `git checkout --track origin/develop`

**Comment by Dhruvin14** [comment]
git branch -D develop

I do not have devlop in master.

**Comment by Bachibouzouk** [comment]
> git branch -D develop
> 
> I do not have devlop in master.
@Dhruvin14 
can you give me the output of `git branch`?

**Comment by Dhruvin14** [comment]
git checkout --track origin/develop
I have develop branch now with master.
git status 


On branch develop                                                               
Your branch is up to date with 'origin/develop'.                                                                                                                  nothing to commit, working tree clean
git branch

develop    
feature/OE_platform_homepage_link                                                
feature/fix/oep-homepage-link                                                    
master
--

**Comment by Dhruvin14** [comment]
@Bachibouzouk- shall I pull now develop
git pull origin develop

**Comment by Bachibouzouk** [comment]
@Dhruvin14 
can you also show me the output of `git remote -v`?

`master` and `develop` are distinct branches, I don't understand your sentence "I have develop branch now with master."

You want to make sure your are locally linked with https://github.com/OpenEnergyPlatform/oeplatform.git and not with your previous setting

**Comment by Dhruvin14** [comment]
@Bachibouzouk 
git remote -v

old_remote      https://github.com/Dhruvin14/oeplatform.git (fetch)              
old_remote      https://github.com/Dhruvin14/oeplatform.git (push)              
origin  https://github.com/OpenEnergyPlatform/oeplatform.git (fetch)             
origin  https://github.com/OpenEnergyPlatform/oeplatform.git (push)

master and develop are distinct branches, I don't understand your sentence "I have develop branch now with master.
I misinterpreated that and both branches are diffrent.

**Comment by MGlauer** [comment]
Just for clarification and future reference: 
@Dhruvin14 uses his own fork, normally, this repository should also be set as origin, as `forkers` do not necessarily have push permissions on our organisation. Thus, setting it as origin may be ill-advised. In order to pull the most resent version on develop from our organisation, I would recommend the [following  approach](https://help.github.com/en/articles/fork-a-repo):

1. `git remote add OpenEnergyPlatform https://github.com/OpenEnergyPlatform/oeplatform.git` 
2. `git fetch OpenEnergyPlatform`
3. `git merge OpenEnergyPlatform/develop`

After merging and resolving potential conflicts you can issue the pull request on GH.
Also, yes, develop and master are two different branches. The master branch hold the release state of the platform (i.e. the version that is currently online). For more information about our branching model look at the [Driessen workflow](https://nvie.com/posts/a-successful-git-branching-model/)

**Comment by Dhruvin14** [comment]
@MGlauer,  Thankyou Martin
As I discussed with @Bachibouzouk   I deleted oeplatform from the source tree and also from my local system. I set up the oeplatform again.

**Comment by Bachibouzouk** [comment]
@MGlauer - as @Dhruvin14 works for @klarareder I added him to the dev team

**Comment by Bachibouzouk** [comment]
@Dhruvin14 I close this PR as the base.html file has changed too much

**Pull request closed without merging**
