### PR TITLE
Improve openAPI schema in docs

### PR DESCRIPTION
**Pull request by ebroda**
As I had a look in the docs, I saw this quite simple openAPI schema.

I added some individual tags to give it some sorting as well as set the document title, included servers for a direct test and changed the operationIDs to avoid duplicates.

### Documentation updates
- Improved OpenAPI documentation of oeplatform REST-API [(#1793)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1793)
 
### PR-Assignee

- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform/)

### Reviewer

- [x] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [x] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Review by jh-RLI — APPROVED** [review]
Nice! That adds good value. I'll also improve the scheme by the end of September to make it a bit more useful.

**Comment by jh-RLI** [comment]
Ah, one thing. Could you update the changelog. Search for the file ‘current.md’. You can just add a short note in the ‘Documentation’ section.

**Comment by ebroda** [comment]
Yes, I'll add an entry on Monday.

**Comment by ebroda** [comment]
@jh-RLI : I updated the changelog accordingly (and also update the branch with the current state of develop).

**Pull request merged**
