### PR TITLE
Move endpoint variable to settings

### PR DESCRIPTION
**Pull request by h-spinde**
## Summary of the discussion

As part of solving issue [1394](https://github.com/OpenEnergyPlatform/oeplatform/issues/1394), the variables query_endpoint and update_endpoint should be moved from views.py to settings.py

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform-code/) 

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
That's great :) I would also like to draw your attention to some efforts I have made to make the code more modular:

I created a subfolder factsheet/oekg where this file is located https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/factsheet/oekg/connection.py

I think we should use this for managing the connections. There you will see the same endpoints, these should also be imported from the settings. Then in the factsheet/views.py I suggest to import the factsheet/oekg/connection.py and use this for the oekg connection. In addition, we can then also remove this section https://github.com/OpenEnergyPlatform/oeplatform/blob/031ffe29b5597656e0f4634c025f1d67df218fe4/factsheet/views.py#L91-L108 as I have moved it to https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/factsheet/oekg/namespaces.py. 

What do you think @adelmemariani ?

**Comment by adelmemariani** [comment]
> What do you think @adelmemariani ?

If you tested it and everything is working it is ok. But, shouldn't the 'bind_all_namespaces' return a graph?

**Comment by jh-RLI** [comment]
Further tests would certainly also be part of this branch, but in general everything has worked so far. I'm happy to help. 

You're right about your comment, it's been a while, I think there was another problem. 

It would be great if we could slowly make the code more modular starting with this branch.

**Comment by jh-RLI** [comment]
As we are now using a different approach, this PR is outdated. Nevertheless, it was good that there was just another developer who suggested another working solution.

See: https://github.com/OpenEnergyPlatform/oeplatform/pull/1656

**Pull request closed without merging**
