### PR TITLE
Release/0.9.1

### PR DESCRIPTION
**Pull request by christian-rli**
Joint release in first OEP developer meeting.

### Bugs
- Fix [#717: https://github.com/OpenEnergyPlatform/oeplatform/issues/717]
- Fix bug where entries in framework factsheets can be edited but are then not displayed.
- Fix tests for CI

### Features
- api command for users to move tables between schemas

### CODE REVIEW

**Comment by christian-rli** [comment]
@MGlauer : The release branch now contains the updated requirements and is ready for testing on toep. The latest commits don't show up in this PR. However they are in the release branch (https://github.com/OpenEnergyPlatform/oeplatform/tree/release/0.9.1) and here that that's enough. I also verified that info looking into another issue (https://github.com/github/hub/issues/198 "you don't need hub to update pull requests. Pull requests are tied to the remote branch they're opened from")

Please let @wingechr know when it's ready for testing and @wingechr please let me or both of us know when I can commence with the release :)

**Comment by wingechr** [comment]
looks ok

**Review by wingechr — APPROVED** [review]
looks ok

**Comment by christian-rli** [comment]
> looks ok

Nice. Sorry for probing, but did you already test it on toep? I would just be impressed by the speed.

**Comment by wingechr** [comment]
> 
> 
> > looks ok
> 
> Nice. Sorry for probing, but did you already test it on toep? I would just be impressed by the speed.

only on my local system

**Comment by MGlauer** [comment]
First Feedback: The current version does not work with Django 3.0.* but it does with version 3.2.*. This should be amended in the requirements.txt

**Comment by MGlauer** [comment]
The test server has been updated

**Comment by wingechr** [comment]
> 
> 
> First Feedback: The current version does not work with Django 3.0.* but it does with version 3.2.*. This should be amended in the requirements.txt

I think we should choose one of two options:

* A) we fix all versions in requirements so that the environment is predictable
* B) we always upgrade to the currently latest version allowed by requirements at the time of the test / release

I assumend B) was already the case, but apparently not? This would also be my preferred option. Any thoughts?

**Comment by christian-rli** [comment]
I also prefer option B and thought that this was the case. So I'd suggest to go with that from now on.

**Review by wingechr — APPROVED** [review]

**Comment by MGlauer** [comment]
There are arguments to make for both options.
Option B guarantees that important security updates are installed as soon as they are available, *but* having the cutting edge version of any software package may introduce incompatibilites and even new security issues.

That is why most production environments settle with option A, in which you have a fixed set of packages that are thoroughly tested and work well together. Yet, there has to be some entity that keeps track of important security updates and manages necessary upgrades.

**Comment by MGlauer** [comment]
But this is probably something that should be discussed in a different place. Still, here is some read how different linux distributions handle this issue: https://averagelinuxuser.com/rolling-vs-fixed-linux-release/

**Comment by christian-rli** [comment]
> There are arguments to make for both options.
> Option B guarantees that important security updates are installed as soon as they are available, _but_ having the cutting edge version of any software package may introduce incompatibilites and even new security issues.
> 
> That is why most production environments settle with option A, in which you have a fixed set of packages that are thoroughly tested and work well together. Yet, there has to be some entity that keeps track of important security updates and manages necessary upgrades.

Thanks for the comments/explanation! I put it on the agenda for the next OEP DEV meeting.

**Comment by christian-rli** [comment]
I also tested moving tables now and the release can go on.

**Comment by christian-rli** [comment]
I checked the release description file, but final steps aren't fully described. What comes first - inform @MGlauer / merge into master / push release button? i'd be happy about a 3 line description or a quick call any time today.

**Comment by MGlauer** [comment]
Production has been updated

**Pull request merged**
