### PR TITLE
Feature 1675 profile tables titles

### LINKED ISSUE #1542: Functionality of the "Delete table" button for topics other than model_draft not clear
## Description of the issue

It is currently not possible to delete tables that are in a topic other than model_draft. However, the "Delete" button is still visible.

## Steps to Reproduce
1.
2.
3.

## Ideas of solution

Determine whether a table can be deleted in other topics. What would the process look like. I assume that published data should not be so easy to delete. 

As an alternative, i suggest showing an unpublish like functionality. We would need to establish a publishing guideline for how to proceed with requests to withdraw the data. 

My opinion is that if data is published it should be always available if it is valid information in the context of the applied assumptions and version of the executed model code.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### LINKED ISSUE #1675: On the Profile/Tables page, long table titles are not fully visible to the user.
## Description of the issue

The user cannot view the full table title on the profile/tables page:
image

## Ideas of solution

E.g. make the tile exandable OR show the title on hover?

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### LINKED ISSUE #1702: New table sidebar extended too much if the page content is ‘long’
## Description of the issue

image

## Ideas of solution

Keep the height of the sidebar appropriate and avoid empty space.

## Context and Environment

- Version used: current develop
- Operating system: Windows
- Environment setup and (python) version: 3.10

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by bmlancien**
## Summary of the discussion

The user cannot view the full table title on the profile/tables page

### Changes

- Change the profile tables by improving color contrast, splitting the tables in 2 rows on very large screens and making the whole title visible (https://github.com/OpenEnergyPlatform/oeplatform/pull/1706)

### Features

- Profile page Tables: Add "unpublish" button to published tables. [(#1706)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1706)

### Automation

Closes #1675 
Closes #1702

In addition
Closes #1542

### PR-Assignee

- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform/)

### Reviewer

- [x] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [x] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by bmlancien** [comment]
- I added a placeholder of an empty state to the profile tables view. I would show it only if there is no table at all. If already one in draft or published then remove it.
- I thought it could be a good idea to add a "add data set" button in that case. The JS function for that button is not working on that page, though. I didn't look any further.
- Also added "Early Access" to the review tab. I simply used CSS for that as you mentioned one badge from Bootstrap didn't have rounded borders

**Comment by bmlancien** [comment]
Sorry @jh-RLI , I didn't realize it was not the right branch for #1702 (I should have created a new one)
Is it okay to use this PR for fixing this too? These were small changes.

**Comment by jh-RLI** [comment]
It is okay to combine the changes. Sometimes it makes things more simple :) Just document the issues that are closed by this PR -> see the text "closes #1702" in your intial comment here.

**Comment by bmlancien** [comment]
Alright! And I didn't even know that moving the issue to "Done" would close it automatically...

**Comment by jh-RLI** [comment]
Sorry, I should have explained to you that Github has added this automation. I would suggest that you only move topics to the ‘In Progress’ column. Because once the PR is closed, these topics are also automatically closed by the keyword ‘Closes #ISSUENR’ you can find in the PR description under Workflow checklist.

**Comment by bmlancien** [comment]
Ah ok, good to know for next time! Learning by making mistakes...

**Pull request merged**
