### PR TITLE
Add very simple selenium test structure

### LINKED ISSUE #474: There is no structure to run selenium based tests on the website

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Closes #474

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@MGlauer - where would be the best place to store such test files?

**Comment by Bachibouzouk** [comment]
@MGlauer ?

**Comment by MGlauer** [comment]
Right now tests are done in the respective app (as is standard in django). We could add a tests/ folder at top level.

**Comment by MGlauer** [comment]
Is it possible/advisable to add this to travis?

**Comment by Bachibouzouk** [comment]
> Is it possible/advisable to add this to travis?

yes and yes

**Comment by Bachibouzouk** [comment]
> Is it possible/advisable to add this to travis?

@MGlauer - I will wait that #502 is merged to avoid conflicts in the .travis.yml file

**Comment by wingechr** [comment]
reopen as needed

**Pull request closed without merging**
