### PR TITLE
improve table.oemetadata loading time #735

### PR DESCRIPTION
**Pull request by jh-RLI**
- [x] Store oemetadata in dataedit.models.tables oemetadata (JSONB) field (update api post and get still reads from SQL comment on table)
- [x] Add functionality to get correct oemetadata key order as JSONB does not preserver order.
- [x] Adapt metadata and MetaWidget functionality

Addtional:
- [x] fixes popover in bootstrap5
- [x] Add Tests

### CODE REVIEW

**Comment by jh-RLI** [comment]
@wingechr Please review this as soon as i mark as normal Pull Request (not draft). 

At the moment, I would be interested in your opinion to extend [this table](https://github.com/OpenEnergyPlatform/oeplatform/blob/c4f61fbcf29016c80644081a00d30223759520e5/dataedit/models.py#L40-L56) and to store the metadata string in a JSON field there instead of creating a new table for oemetadata. My question is, do you think we will keep this table after we resolved the schemas.

Regarding the schema solution, we could reuse some django tables that store info on all existing tables and the schema they are stored in. The [schema table](https://github.com/OpenEnergyPlatform/oeplatform/blob/c4f61fbcf29016c80644081a00d30223759520e5/dataedit/models.py#L35-L37) (rename to topics) in combination with the [tables ](https://github.com/OpenEnergyPlatform/oeplatform/blob/c4f61fbcf29016c80644081a00d30223759520e5/dataedit/models.py#L40-L56) table to implement topics (tag tables with corresponding topic). 

I have spoken with ludwig and we are definitely in favor of keeping the topics, since a lot of work went into the elaboration back then.

**Comment by wingechr** [comment]
Yes, definitely use this the Table object. This is the django representation of an oedb table and we will definitely keep it. creating a new model class  is not necesary because it's one-to-one relation.

**Comment by wingechr** [comment]
I'll review it as soon as possible

**Comment by jh-RLI** [comment]
Thanks a lot, I will eventually look again and maybe refactor some code so it is more organized. In gernal it works. I'm not so fan of keeping the SQL comment on table and the DB json field together (as a store for the metadatan) but did it that way now, as it was initially my plan to keep the old functionality.

**Comment by wingechr** [comment]
in addition to some black formatting, i changed (simplified?) the way the nested parsing of the metadata (try 1.5, then 1.4) is done in the `api/actions.py`.

To me, this seems more readable now, but we should look at this together

**Comment by jh-RLI** [comment]
Yes! i think it is more readable, i wasn't able to come up with a better way for the exception block and looked deeper into exceptions - based on what i learned there your solution is simple and great :D .

**Review by wingechr — APPROVED** [review]

**Comment by jh-RLI** [comment]
@wingechr what do you think, should we merge this already? I've started revising the migration script (Martin's outdated one) and added it to the new Django migration. I could add this, but this PR is getting kinda big.

**Comment by jh-RLI** [comment]
I think i will add the migration here.

**Comment by jh-RLI** [comment]
I will merge this PR now and add the migration stuff to a new one.

**Pull request merged**
