### PR TITLE
Release/v0.10.0

### PR DESCRIPTION
**Pull request by adelmemariani**

### CODE REVIEW

**Comment by adelmemariani** [comment]
@wingechr Please check if the failed test is related to 'tutorials' and 'ipython_genutils'.

**Comment by jh-RLI** [comment]
@adelmemariani 
- I fixed the CI issue. I hope this does not cause any problems to the tutorials app, I did some testing at least. 
- Can you tell me if this PR contains functional changes to the code that should be included in another PR for hotfix v0.10.1? I want to make sure we don't mess up the release. Officially v0.10.0 is already released (on the OEP website) so only changes to the documentation should be included here (like changelog etc.) functional changes (also bugfix) will be included in the hotfix release.

**Comment by adelmemariani** [comment]
In terms of functional changes, yes this PR fixes some (minor) bugs in the factsheets. However, still, some issues exist due to the fact that the data that we have on the RDF dataset is old and we can not populate the energy carries in the dropdowns. We still don't have a specific hotfix for these changes.

**Comment by jh-RLI** [comment]
Okay, any other changes coming from your side here? Otherwise I start with the open tasks to complete the release v0.10.0 properly. (Github release + release tag)

**Pull request merged**
