### PR TITLE
comment section with the reply feature

### PR DESCRIPTION
**Pull request by SharanyaMohan-30**

### CODE REVIEW

**Comment by christian-rli** [comment]
I was unable to test this, because of an error in migrations. 
`django.db.migrations.exceptions.NodeNotFoundError: Migration tutorials.0009_merge_20210625_0847 dependencies reference nonexistent parent node ('tutorials', '0008_auto_20210317_1225')
`
Is the same true for others as well or is it time for me to reset my local setup once more?

**Comment by MGlauer** [comment]
This may be caused by switching to an older branch A. Your DB is still on a more recent migration that has not been commited that depends on a migration that was introduced after A was branched. The easiest solution: Re-checkout the branch where this migration was present, roll back your migration to that point that matches the migrations on branch A.

**Comment by christian-rli** [comment]
Thank you @MGlauer  I managed to get the branch running after setting up my database again. Since this PR was not connected to an issue, I'm not sure what exactly is new, but I'm suspecting something in the table view? I created a table and took a look, but I don't see any changes to the current view. Could any of you refer to an issue or describe the changes?

**Comment by SharanyaMohan-30** [comment]
Hello @christian-rli this branch is related to comment (comments and reply only for users)section which has been added under the Meta Information section i.e. while rendering the table (https://openenergy-platform.org/dataedit/view/boundaries/bkg_gn250_b). 
Could you please confirm if you can view the comment section under the Meta information ?

**Comment by christian-rli** [comment]
Thanks for the replu @SharanyaMohan-30 . I do not see any comment section. Here are screenshots of what I'm seeing. Any idea why it could be missing when I run it locally? I don't see any errors.

Bildschirmfoto zu 2021-08-31 18-04-15
Bildschirmfoto zu 2021-08-31 18-04-08

**Comment by SharanyaMohan-30** [comment]
Hi @christian-rli sorry for the inconvenience there were few issues while pushing the code hence I regret to inform that all the necessary files weren't added to the branch .Please find the necessary files under the new PR feature/displaytitle-commentsection.

**Pull request closed without merging**
