### PR TITLE
Feature/metadata presentation UI#1109

### LINKED ISSUE #1109: Improve metadata presentation

### PR DESCRIPTION
**Pull request by bmlancien**
@Ludee Here is the first change on the data/medata view. @jh-RLI can you have a look and check that nothing has been broken on other pages? Thanks!

Close #1109

### CODE REVIEW

**Review by jh-RLI — APPROVED** [review]
Great improvements to the general layout structure and the UI !

**Comment by jh-RLI** [comment]
@bmlancien I will merge this now if you are okay with it?

**Comment by bmlancien** [comment]
> Great improvements to the general layout structure and the UI !

Thanks :)

> I will merge this now if you are okay with it?

Yes, please!

**Comment by jh-RLI** [comment]
@bmlancien dont mind me adding two commits to this PR ... Also there is a CI error regarding the automated test. That must be fixed before merging.

**Pull request merged**
