### PR TITLE
Add and update logos on About #912

### LINKED ISSUE #907: New project logo is missing on about
- [x] Add project logo SIROP

### LINKED ISSUE #912: Partner logos update in about page
- [x] Add fortis logo @FlorianK13
- [x] Update logo HZG -> hereon
- [x] Fix project logo SIROP
- [x] Open Energy Family - Group Foto

### PR DESCRIPTION
**Pull request by Ludee**
closes #912 
closes #907

### CODE REVIEW

**Comment by Ludee** [comment]
Please run complete test to check if files are loading from the correct logos folder:

- [ ] SIROP
- [ ] fortiss

**Comment by jh-RLI** [comment]
The image for fortiss is missing. 
image

**Review by jh-RLI — COMMENTED** [review]
What do you mean by run full tests? I run `python manage.py collectstatic ` and agree with putting the logos in base/static/ .

**Comment by Ludee** [comment]
Updated the fortiss logo and path. Please check again.

**Pull request merged**
