### PR TITLE
Fix one line api code

### LINKED ISSUE #1646: Display python access example not as one liner
## Description of the issue
Currently the Python example for using the data is shown as a one liner, even though the source has line breaks.

grafik

Or is this wanted? Else you should consider decrease the amount of rows.

If you want to have everything marked at one, consider include [onclick="this.select()"](https://stackoverflow.com/a/7313795)

## Steps to Reproduce
1. Open any database item, e.g. https://openenergy-platform.org/dataedit/view/boundaries/bkg_gn250_b

## Ideas of solution
Increase rows by one, remove white-space: nowrap;

Consider removing also resize: none; cause if necessary people should be able to increase the field size

see code in referenced commit. If you agree, you might directly merge or I'll create a pull request out of it.

## Context and Environment
* Version used: current online one
* Operating system: -
* Environment setup and (python) version: -

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ebroda**
## Summary of the discussion
see #1646

### Automation

Closes #1646

### PR-Assignee

- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform/)

### Reviewer

- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by bmlancien** [comment]
@jh-RLI I'm not able to review the PR as I get an error:

`ImportError: cannot import name 'DBPEDIA_LOOKUP_SPARQL_ENDPOINT_URL' from 'oeplatform.settings'`

Probably coming from last develop merge.

**Comment by jh-RLI** [comment]
> @jh-RLI I'm not able to review the PR as I get an error:
> 
> `ImportError: cannot import name 'DBPEDIA_LOOKUP_SPARQL_ENDPOINT_URL' from 'oeplatform.settings'`
> 
> Probably coming from last develop merge.

The securitysettings had been updated. You can add this part to your oeplatform/securitysettings.py file around line  79 beow the RDF_DATASETS dict

```
# The RDF database brings a server that provides a web api.
# This service is part of the internal network.
if RDF_DATABASES:
    OEKG_SPARQL_ENDPOINT_URL = f"http://{RDF_DATABASES['knowledge']['host']}:{RDF_DATABASES['knowledge']['port']}/{RDF_DATABASES['knowledge']['name']}/sparql"

# The ontop-vkg is used to translate sparql to sql queries
# https://ontop-vkg.org/guide/cli.html#ontop-endpoint
# This service is part of the internal network.
# It depends on a mapping that maps concepts to the relational data structure
# We use it to implement quantitative scenario comparison
USE_ONTOP = False

if USE_ONTOP:
    ONTOP_SPARQL_ENDPOINT_URL = "http://localhost:8080/sparql"

# The LOEP provides lookup (autocomplete search) functionality implemented
# using Apache Lucene.
# https://github.com/dbpedia/dbpedia-lookup/tree/legacy
# This service is part of the internal network.
# It can find classes from the OEO and return similar concepts based on
# the text an user inputs to a search field
USE_LOEP = False
if USE_LOEP:
    DBPEDIA_LOOKUP_SPARQL_ENDPOINT_URL = (
        "http://localhost:8082/lookup-application/api/search?query="
    )
else:
    DBPEDIA_LOOKUP_SPARQL_ENDPOINT_URL = ""
```

**Review by bmlancien — CHANGES_REQUESTED** [review]
Thanks for noting that the layout was not correctly displayed on Firefox.

But in order to change the styling, the scss has to regenerate bootstrap.min.css, which is not the case now. You can check the [read.me](https://github.com/OpenEnergyPlatform/oeplatform/tree/develop/theming) in the theming folder.

**Comment by ebroda** [comment]
I now managed to change the bootstrap.min.css, it's commited above.

But I didn't manged to get this done using the docker image and process described above. But that'll be an own issue.

**Comment by ebroda** [comment]
see #1854 and #1855

**Comment by bmlancien** [comment]
Did you change the bootstrap.min.css directly? Because I cannot see the changes in the browser. It still appears in one line on Firefox.

**Comment by jh-RLI** [comment]
There seems to be a conflict in the bootstrap.min.css maybe that is why?

**Comment by bmlancien** [comment]
> There seems to be a conflict in the bootstrap.min.css maybe that is why?

Maybe! Because I restarted and tried again, and now it is working.

**Comment by bmlancien** [comment]
I solved the conflict, @jh-RLI can you double-check and merge? Thanks!

**Comment by ebroda** [comment]
If I compare that file with the one in develop, there are a lot of differences - so looks like the merging was bad. 
Probably, it's the best to rebuild the file or use the on in develop and apply the changes to that one, as pushed to the branch.

Test:
```sh
wget -O pr.css https://raw.githubusercontent.com/OpenEnergyPlatform/oeplatform/56d83b5fd7639ae7226e8a8bd5eabc3a82d37586/base/static/css/bootstrap.min.css
wget -O develop.css https://raw.githubusercontent.com/OpenEnergyPlatform/oeplatform/2c8d31e1cb5da69d658761ec5749d4bcfdbafc43/base/static/css/bootstrap.min.css

sed 's/\([;}]\)/\1\n/g' pr.css > pr.lcss
sed 's/\([;}]\)/\1\n/g' develop.css > develop.lcss

diff pr.lcss develop.lcss
```

as expected:
6167c6167
< .table-sidebar__collapse textarea{white-space:pre;
---
> .table-sidebar__collapse textarea{white-space:nowrap;

**Review by ebroda — COMMENTED** [review]
Updated in a266fd5707cc7db03ee940d825a186913b74276c and 56d83b5fd7639ae7226e8a8bd5eabc3a82d37586

**Comment by bmlancien** [comment]
If I try to rebuild bootstrap.min.css or to merge develop and rebuild the file, I don't see any changes changes in that file. I guess it means it is up-to-date?

**Comment by ebroda** [comment]
Yes, basically the file should be fine then.

**Pull request merged**
