### PR TITLE
Add missing link to oep-api tutorials in dataview

### LINKED ISSUE #259: Database / Dataview, Links zu Tutorials funktionieren nicht
Unter den Datensätzen gibt es einen Erklärungstext, dessen zweite Hälfte auf Tags eingeht.
Darunter soll es in Stichworten Links zu verschiedenen Tutorials rund um die OEP geben.
Die Stichpunkte sind jedoch noch keine Hyperlinks

### PR DESCRIPTION
**Pull request by jh-RLI**
closes #259

On the bottom of the dataview page there are missing links to available tutorials on how to use the oep-api.

### CODE REVIEW

**Comment by jh-RLI** [comment]
@christian-rli Can you check if you agree with the linked tutorials for each point.

**Comment by christian-rli** [comment]
I agree with the links you provided, but cannot seem to get this branch working. Might just be my setup though.

**Comment by MGlauer** [comment]
> I agree with the links you provided, but cannot seem to get this branch working. Might just be my setup though.

Can you specify which error messages you get?

**Comment by christian-rli** [comment]
The error does not stem from this specific branch. I came from an older version of oeplatform and just pulled develop. Almost everything displays fine, but the dateview tab does not.

Django tells me:

```
ProgrammingError at /dataedit/
(psycopg2.ProgrammingError) ERROR:  Column tags.usage_count does not exist
```

So I tried to make migrations:

`python manage.py makemigrations`

but

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0043_auto_20190306_1056, 0043_merge_20190425_1036 in modelview; 0013_delete_view, 0013_auto_20170810_1031 in dataedit).
To fix them run 'python manage.py makemigrations --merge'
```

`python manage.py showmigrations`

shows me that my migrations  for model_view

```
 [X] 0038_auto_20171130_1930
 [X] 0039_auto_20171211_1228
 [X] 0040_auto_20171211_1239
 [X] 0033_auto_20160414_1346
 [X] 0036_merge_20170808_1551
 [X] 0039_merge_20171201_1118
 [X] 0041_merge_20171211_1420
 [X] 0042_auto_20171215_0953
 [X] 0043_auto_20190306_1056
 [ ] 0036_auto_20170322_1622
 [ ] 0043_merge_20190425_1036
```

and for dataedit

```
 [X] 0009_tablerevision_path
 [X] 0010_auto_20170504_1753
 [X] 0011_tablerevision_size
 [X] 0008_view
 [X] 0009_auto_20170404_1222
 [X] 0012_merge_20170910_1002
 [ ] 0013_auto_20170810_1031
 [X] 0013_delete_view
```

ended up in a funny order. So I have to fix those migrations somehow, but I guess it has nothing to do with the branch, or the project for that matter, but only with my local setup.

**Comment by christian-rli** [comment]
Got it working by manually creating the missing tables via pgadmin. Checks out.

**Comment by jh-RLI** [comment]
@MGlauer can you help me fix the ci error? I tried to re-run the test, but it didn't fix it.

**Comment by Bachibouzouk** [comment]
what fails is `The command "wget https://raw.githubusercontent.com/OpenEnergyPlatform/oeplatform-deploy/master/oedb_mini.dump" failed and exited with 8 during .`

**Comment by jh-RLI** [comment]
@Bachibouzouk Thank you :) Are you able to merge this?

**Pull request merged**
