### PR TITLE
add NFDI4Energy to partners

### PR DESCRIPTION
**Pull request by SMutyala18**
## Summary of the discussion

Added NFDI4Energy to the partners section with a redirect link to the NFDI4Energy website

### Added
- Add NFDI to our list of Partners [(#1605)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1605)

### Automation
Part of #1591

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform-code/) 

### Reviewer
- [x] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [x] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
@SMutyala18 can you merge the latest oeplatform:develop into your branch. Then the CI-Tests will pass.

**Comment by jh-RLI** [comment]
Ah, great, I assume it was renamed by you to install the oeplatform? Thanks for fixing some other issues along the way too.

**Review by jh-RLI — CHANGES_REQUESTED** [review]
The last thing missing is the changelog entry `- Add NFDI to our list of Partners [(#1605)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1605)`. You can add this to the file `versions/changelogs/current.md` in the section "Features".

**Comment by SMutyala18** [comment]
> Ah, great, I assume it was renamed by you to install the oeplatform? Thanks for fixing some other issues along the way too.

Yes, I had to rename the file while adding oeo.

**Comment by SMutyala18** [comment]
> The last thing missing is the changelog entry `- Add NFDI to our list of Partners [(#1605)](https://github.com/OpenEnergyPlatform/oeplatform/pull/1605)`. You can add this to the file `versions/changelogs/current.md` in the section "Features".

I have updated the changelog file. Now, it should work.

**Review by jh-RLI — APPROVED** [review]
Yes, it (the CI) already worked after you corrected the name of the sec.settings :) The changelog entry is just a formal step. Great first contribution! I will merge the PR soon.

**Comment by jh-RLI** [comment]
I will keep the corresponding issue open until the "Coming Soon" page is also implemented.

**Comment by SMutyala18** [comment]
> Yes, it (the CI) already worked after you corrected the name of the sec.settings :) The changelog entry is just a formal step. Great first contribution! I will merge the PR soon.

thanks :)

**Pull request merged**
