### PR TITLE
remove test column names

### LINKED ISSUE #1156: datatables are broken
in current develop branch: 

* javascript throws alerts
* column headers are messed up:

grafik

### PR DESCRIPTION
**Pull request by wingechr**
closes #1156

@bmlancien: I removed the hard coded column names, that seems to fix the issue

### CODE REVIEW

**Review by jh-RLI — APPROVED** [review]
LGTM :)

**Comment by Ludee** [comment]
These still exist on the TOEP.
Should they be removed manually or is there a better way to delete them all?

**Comment by wingechr** [comment]
@Ludee I don't think i quiet understand. the problem was that only hard coded column names in the html templates in the data viewer...

**Comment by jh-RLI** [comment]
They will exists on toep till the next test release is published :) We should merge this and tell adel to install the latest develop branch in the toep.

**Comment by jh-RLI** [comment]
Off topic, but: +1 on test release automation on TOEP:
- any update in development should trigger a release on TOEP 
- the only thing holding us back is some concerns about Alembic migration (they don't seem to be fully down and upgradable)  @wingechr you tackled this some time ago, but I think we need to check if this is working now as requested by @MaGering

**Pull request merged**
