### PR TITLE
ci: bump github actions versions

### PR DESCRIPTION
**Pull request by afuetterer**
## Summary of the discussion

Hi, this is my first PR to the project. Please let me know, if the changes are desired.

This PR bumps the GitHub actions versions in your workflows. This change will reduce the number of warnings in CI, e.g. "The following actions uses node12 which is deprecated ..." (https://github.com/OpenEnergyPlatform/oeplatform/actions/runs/10722144730).

What do you think?

### Features

- Add a new functionality [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Changes

- Update existing functionality [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Bugs

- Fixed a problem with [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Removed

- Remove a broken link [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Documentation updates

- Updated documentation for [(#)](https://github.com/OpenEnergyPlatform/oeplatform/pull/)

### Automation

Closes #

### PR-Assignee

- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md)
- [ ] 📙 Update the documentation on [mkdocs](https://openenergyplatform.github.io/oeplatform/)

### Reviewer

- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by jh-RLI** [comment]
Thank you very much. I will have a look at it. In general, this seems to be a good improvement.

**Comment by jh-RLI** [comment]
So far I haven't noticed anything that speaks against this update. As the test has also been passed, I will now approve it, thanks again :)

**Comment by jh-RLI** [comment]
Btw for these kind of updates I'm fine with skipping the changelog entry for major ones have a look at the [current.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/versions/changelogs/current.md) changelog which contain all the changes that are staged for the next release.

**Comment by afuetterer** [comment]
Thanks. Yes, I agree to not add these kind of changes to a changelog to keep the reader's attention focused on the "real" changes of the project.

**Comment by afuetterer** [comment]
Btw I used the [gha-update](https://github.com/davidism/gha-update) locally for updating the actions.

In case you want to have a scheduled update job, you could add a grouped dependabot setting for github actions, e.g. monthly or quarterly. If you like, I can submit a PR.

**Pull request merged**
